In [1]:
import pandas as pd

In [2]:
import py3Dmol

In [3]:
df = pd.read_csv('ZnPc-gable-td035.gjf', header=None, sep=r'\s+')
df

     0         1         2         3
0    C  3.255751  0.032844  1.293259
1    C  3.255751  0.032844 -1.293259
2    H  3.225592  0.032910 -2.387650
3    H  3.225592  0.032910  2.387650
4    C  2.602144  1.261492  0.706647
..  ..       ...       ...       ...
120  H  5.094259 -1.781594 -1.992215
121  C  5.514324 -1.240053  1.137349
122  H  5.227701  0.927158  1.176667
123  H  5.094259 -1.781594  1.992215
124  H  6.568635 -0.996340  1.353478

[125 rows x 4 columns]

In [5]:
df[[1, 2, 3]] = df[[2, 3, 1]]

In [6]:
viewer = py3Dmol.view()

viewer.addModel(str(len(df)) + '\nx\n' + df.to_string(header=None, index=False), 'xyz')

viewer.setStyle({'stick': {'radius': 0.1}})
viewer.zoomTo()
viewer.show()

In [7]:
with open('1.xyz', 'w') as fp:
    print(df.to_string(formatters={
        0: '  {:2s}'.format,
    }, float_format='{:13.6f}'.format, header=None, index=False), file=fp)

In [8]:
df

     0         1         2         3
0    C  0.032844  1.293259  3.255751
1    C  0.032844 -1.293259  3.255751
2    H  0.032910 -2.387650  3.225592
3    H  0.032910  2.387650  3.225592
4    C  1.261492  0.706647  2.602144
..  ..       ...       ...       ...
120  H -1.781594 -1.992215  5.094259
121  C -1.240053  1.137349  5.514324
122  H  0.927158  1.176667  5.227701
123  H -1.781594  1.992215  5.094259
124  H -0.996340  1.353478  6.568635

[125 rows x 4 columns]