In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('bsse.txt', header=None, delim_whitespace=True)
df

                   0      1
0     ZnPc2_35_0.out -1.996
1   ZnPc2_35_100.out -0.379
2    ZnPc2_35_10.out -1.927
3   ZnPc2_35_120.out -0.172
4    ZnPc2_35_15.out -1.878
5    ZnPc2_35_20.out -1.797
6    ZnPc2_35_25.out -1.690
7    ZnPc2_35_30.out -1.588
8    ZnPc2_35_40.out -1.393
9    ZnPc2_35_50.out -1.190
10   ZnPc2_35_60.out -0.993
11   ZnPc2_35_70.out -0.931
12   ZnPc2_35_80.out -0.728

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       13 non-null     object
 1   1       13 non-null     float64
dtypes: float64(1), object(1)
memory usage: 336.0+ bytes

In [4]:
df[0] = df[0].str.split('.')
df

                      0      1
0     [ZnPc2_35_0, out] -1.996
1   [ZnPc2_35_100, out] -0.379
2    [ZnPc2_35_10, out] -1.927
3   [ZnPc2_35_120, out] -0.172
4    [ZnPc2_35_15, out] -1.878
5    [ZnPc2_35_20, out] -1.797
6    [ZnPc2_35_25, out] -1.690
7    [ZnPc2_35_30, out] -1.588
8    [ZnPc2_35_40, out] -1.393
9    [ZnPc2_35_50, out] -1.190
10   [ZnPc2_35_60, out] -0.993
11   [ZnPc2_35_70, out] -0.931
12   [ZnPc2_35_80, out] -0.728

In [5]:
df[0] = df[0].str[0].str.split('_').str[-1]

In [6]:
df[0] = df[0].astype(int)

In [7]:
df[0] = df[0] / 10

In [8]:
df.sort_values(0, inplace=True)

In [9]:
df[1] = - df[1] * 2

In [10]:
df.to_excel('bsse.xlsx', index=False, header=None)

In [11]:
df

       0      1
0    0.0  3.992
2    1.0  3.854
4    1.5  3.756
5    2.0  3.594
6    2.5  3.380
7    3.0  3.176
8    4.0  2.786
9    5.0  2.380
10   6.0  1.986
11   7.0  1.862
12   8.0  1.456
1   10.0  0.758
3   12.0  0.344